version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    depends_on:
      - blacklist
  blacklist:
    build: ./blacklist
    volumes:
      - ./app/db:/db
    expose:
      - "5001"
