version: '3.8'
services:
  web:
    build: .
    expose:
      - "80"
    volumes:
      - ./app:/app
    environment:
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}
    depends_on:
      - blacklist
  blacklist:
    build: ./blacklist
    volumes:
      - ./app/db:/db
    expose:
      - "5001"
    environment:
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}
  sanitizer:
    build: ./sanitizer
    environment:
      - UPSTREAM_URL=http://web:80
      - SANITIZER_CONFIG=/etc/gatekeeper/config.yml
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}
    volumes:
      - ./sanitizer/config.example.yml:/etc/gatekeeper/config.yml:ro
    expose:
      - "8080"
    depends_on:
      - web
  bunkerweb:
    image: bunkerity/bunkerweb:latest
    expose:
      - "8080"
    environment:
      - API_WHITELIST_IP=0.0.0.0/0
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}
    volumes:
      - bw-data:/var/lib/bunkerweb
    command: >
      /bin/sh -c "chown -R 101:101 /var/lib/bunkerweb && /entrypoint.sh"
    depends_on:
      - sanitizer
    networks:
      - default
      - bw-plugins
  bunkerweb-scheduler:
    image: bunkerity/bunkerweb-scheduler:latest
    environment:
      - BUNKERWEB_INSTANCES=bunkerweb
      - SERVER_NAME=${DOMAIN:-localhost}
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_HOST=http://sanitizer:8080
      - USE_DB=true
      - API_WHITELIST_IP=0.0.0.0/0
      - HTTP2=no
      - USE_MODSECURITY=no
      - USE_CORAZA=yes
      - CORAZA_API=http://bw-coraza:8080
      - USE_CLAMAV=yes
      - CLAMAV_HOST=clamav
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}
    volumes:
      - bw-data:/data
    depends_on:
      - bunkerweb
    networks:
      - default
      - bw-plugins
  bunkerweb-ui:
    image: bunkerity/bunkerweb-ui:latest
    ports:
      - "8000:80"
    environment:
      - BUNKERWEB_URL=http://bunkerweb:8080
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}
    volumes:
      - bw-data:/var/lib/bunkerweb
    depends_on:
      - bunkerweb-scheduler
  annoyingsite:
    build: ./annoyingsite
    expose:
      - "4000"
    environment:
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}
  gateway:
    build: ./gateway
    ports:
      - "80:80"
    environment:
      - BUNKER_URL=http://bunkerweb:8080
      - ANNOY_URL=http://annoyingsite:4000
      - BANNED_IPS_FILE=/banned/banned_ips.list
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}
    volumes:
      - ./banned:/banned
    depends_on:
      - bunkerweb
      - annoyingsite
  fail2ban:
    image: crazymax/fail2ban:latest
    volumes:
      - ./fail2ban:/etc/fail2ban
      - ./banned:/banned
    depends_on:
      - gateway
    environment:
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}
  clamav:
    image: clamav/clamav:1.4
    volumes:
      - ./clamav-data:/var/lib/clamav
    networks:
      - bw-plugins
    environment:
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}
  bw-coraza:
    image: bunkerity/bunkerweb-coraza:latest
    networks:
      - bw-plugins
    environment:
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}

  honeypot:
    build: ./honeypot
    network_mode: host
    environment:
      - CMD_NOT_FOUND_ACTION=${CMD_NOT_FOUND_ACTION}

volumes:
  bw-data:
networks:
  bw-plugins:
    name: bw-plugins
